# Generated by Django 4.2.7 on 2023-11-01 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('Stone_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Stone_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('Activation_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Start_Time', models.DateTimeField()),
                ('End_Time', models.DateTimeField()),
                ('Stone_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stone')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
