# Generated by Django 4.2.7 on 2023-11-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stone_stone_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stone',
            name='Stone_State',
        ),
    ]
